server:
  port: 8515

spring:
  application:
    name: service-pay
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # 配置数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # Redis的相关配置
  redis:
    host: localhost
    port: 6379
    #数据库
    database: 0
  config:
    import: application-alipay.yml

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/com.zzf.user.mapper/*/*.xml